<a href="https://colab.research.google.com/github/SolKidonakis/NLP_TPFINAL/blob/main/TP_FINAL_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PROCESAMIENTO DEL LENGUAJE NATURAL: TRABAJO PRACTICO FINAL**

Alumna: Sol Kidonakis

**EJERCICIO 1**

**Carga de librerias**

In [ ]:
!pip install pymupdf sentence-transformers pandas chromadb SPARQLWrapper spacy transformers python-decouple langchain
!python -m spacy download es_core_news_sm


In [ ]:
pip install -U langchain-community

In [ ]:
pip install neo4j


In [ ]:
!pip install PyPDF2


In [5]:
import pandas as pd
from langchain.document_loaders import PubMedLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import OpenAIEmbeddings
from neo4j import GraphDatabase
import nltk
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from langchain.text_splitter import RecursiveCharacterTextSplitter
import numpy as np
import gensim.downloader as api
from SPARQLWrapper import SPARQLWrapper, JSON
import nltk
from nltk import pos_tag
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline
from transformers import AutoModelForCausalLM, AutoTokenizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import joblib
import chromadb
import PyPDF2
import re
from sentence_transformers import SentenceTransformer

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')

**Documentos PDF**

In [7]:
# Cargar el modelo de SentenceTransformers
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

# Función para extraer el contenido de los documentos PDF
def extract_text_from_pdf(pdf_file):
    try:
        with open(pdf_file, 'rb') as file:
            reader = PyPDF2.PdfReader(file)
            text = ""
            for page_num in range(len(reader.pages)):
                page = reader.pages[page_num]
                text += page.extract_text()
        return text
    except Exception as e:
        print(f"Error al abrir el archivo PDF {pdf_file}: {e}")
        return ""

# Función para limpiar el texto
def clean_text(text):
    # Eliminar caracteres especiales y números
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # Tokenizar el texto
    tokens = word_tokenize(text, language='spanish')
    # Eliminar stopwords
    stop_words = set(stopwords.words('spanish'))
    tokens = [word for word in tokens if word.lower() not in stop_words]
    # Reconstruir el texto limpio
    clean_text = ' '.join(tokens)
    return clean_text.strip()

# Nombres de los archivos PDF
pdf_files = ['Argentina.pdf', 'Brasil.pdf']

# Extraer y limpiar el texto de cada PDF
pdf_texts = {}
for pdf_file in pdf_files:
    raw_text = extract_text_from_pdf(pdf_file)
    cleaned_text = clean_text(raw_text)
    pdf_texts[pdf_file] = cleaned_text

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.73k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [8]:
# Dividir el texto en fragmentos de longitud específica usando Langchain
chunk_size = 1000
chunk_overlap = 200

splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap)

processed_texts = {}
for pdf_file, text in pdf_texts.items():
    chunks = splitter.split_text(text)
    processed_texts[pdf_file] = chunks

# Mostrar los primeros fragmentos de texto procesados (opcional)
for pdf_file, chunks in processed_texts.items():
    print(f"Fragmentos procesados de {pdf_file}:")
    for chunk in chunks[:3]:  # Mostrar solo los primeros 3 fragmentos
        print(chunk[:200])  # Mostrar solo los primeros 200 caracteres
    print()


Fragmentos procesados de Argentina.pdf:
Repblica Argentinaa Bandera Escudo Lema Unin Libertadb Himno Himno Nacional Argentino Problemas reproducir archivo Territorio controlado Repblica Argentina verde oscuro territorio reclamado controlado
km Lnea costa km Punto ms alto Aconcagua Argentina Argentina oficialmente Repblica Argentinai pas soberano Amrica Sur ubicado extremo sur sudeste dicho subcontinente Adopta forma gobierno republicana 
Urugua ocano Atlntico oeste sur continental Chile aguas atlnticas Mar Hoces segundo pas mayor ndice Desarrollo Humano IDH regin detrs vecino Chile Aplica modelos salud educacin pblica garantizan acces

Fragmentos procesados de Brasil.pdf:
Repblica Federativa Brasil Repblica Federativa do Brasil portugus Bandera Escudo Lema Ordem progresso espaol Orden progreso Himno Hino Nacional Brasileiro portugus Himno Nacional Brasileo Problemas re
Federativa Brasil Repblica Federativa do Brasil pas soberano Amrica Sur comprende mitad oriental continente grupos peq

**Vectorizacion y almacenamiento en Chroma**

In [9]:

from sentence_transformers import SentenceTransformer

# Cargar el modelo de Sentence Transformers
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')


# Configurar ChromaDB
client = chromadb.Client()

# Crear o recuperar la colección
collection = client.get_or_create_collection("collection")

# Generar embeddings y almacenarlos
embeddings = {}

for pdf_file, chunks in processed_texts.items():
    for i, chunk in enumerate(chunks):
        embedding = model.encode(chunk)
        if embedding is not None:
            doc_id = f"{pdf_file}_chunk_{i}"
            embeddings[doc_id] = embedding.tolist()

# Guardar los embeddings en ChromaDB
batch_size = 100

def batch(iterable, n=1):
    l = len(iterable)
    for ndx in range(0, l, n):
        yield iterable[ndx:min(ndx + n, l)]

for pdf_file in processed_texts.keys():
    document_batch = []
    embedding_batch = []
    id_batch = []

    for i in range(len(processed_texts[pdf_file])):
        doc_id = f"{pdf_file}_chunk_{i}"
        if doc_id in embeddings:
            document_batch.append(processed_texts[pdf_file][i])
            embedding_batch.append(embeddings[doc_id])
            id_batch.append(doc_id)

    if document_batch:
        for doc_batch, emb_batch, id_batch_chunk in zip(
                batch(document_batch, batch_size),
                batch(embedding_batch, batch_size),
                batch(id_batch, batch_size)):

            collection.add(
                documents=doc_batch,
                embeddings=emb_batch,
                ids=id_batch_chunk
            )

        print(f"Documentos del archivo {pdf_file} añadidos correctamente.")
    else:
        print(f"No se encontraron embeddings para {pdf_file}.")



Documentos del archivo Argentina.pdf añadidos correctamente.
Documentos del archivo Brasil.pdf añadidos correctamente.


In [10]:

# Función para buscar en ChromaDB
def search_chromadb(query, collection, model):
    query_embedding = model.encode([query])
    results = collection.query(query_embeddings=query_embedding.tolist())
    return results

**Documento CSV**

In [11]:

# Ruta del archivo CSV
csv_file = 'WorldPopulation2023.csv'

# Cargar datos desde el CSV
population_data = pd.read_csv(csv_file)

def search_csv(query, df):
    # Filtrado dinámico del DataFrame basado en el contenido del prompt
    filtered_df = df[df.apply(lambda row: query.lower() in ' '.join(row.astype(str)).lower(), axis=1)]
    return filtered_df if not filtered_df.empty else None


**Base de datos de Grafos**

In [12]:
from SPARQLWrapper import SPARQLWrapper, JSON

# Configurar el endpoint de SPARQL de Wikidata
sparql = SPARQLWrapper("https://query.wikidata.org/sparql")

def search_graph(query):
    # Construcción dinámica de la consulta SPARQL en función del prompt
    sparql.setQuery(f"""
        SELECT ?subject ?predicate ?object WHERE {{
            ?subject ?predicate ?object .
            FILTER(CONTAINS(LCASE(STR(?object)), "{query.lower()}"))
        }} LIMIT 10
    """)
    sparql.setReturnFormat(JSON)
    results = sparql.query().convert()

    if results["results"]["bindings"]:
        return [{"subject": result["subject"]["value"], "predicate": result["predicate"]["value"], "object": result["object"]["value"]} for result in results["results"]["bindings"]]
    return None


**Lematizacion**

In [13]:
import spacy

# Cargar el modelo de spaCy para español
nlp = spacy.load("es_core_news_sm")

def analyze_query(query):
    doc = nlp(query)
    entities = [ent.text for ent in doc.ents]  # Extraer entidades nombradas
    lemmas = [token.lemma_ for token in doc]  # Obtener lemas
    return entities, lemmas


Cuando tenemos un conjunto de documentos e informacion, podemos usar NER para extraer automáticamente todas las personas, empresas y lugares mencionados. Y luego podemos utilizar lematizacion,que consiste en reducir las palabras a su forma base o lema (por ejemplo, "corriendo" a "correr")

**Clasificador basado en LLM**

In [14]:
import os
import requests
import json

os.environ['HUGGINGFACE_TOKEN'] = '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'


In [15]:
import os
import requests
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Función para generar respuestas con Zephyr
def generate_answer(prompt: str, max_new_tokens: int = 768) -> str:
    messages = [
        {
            "role": "system",
            "content": "Eres un asistente útil que siempre responde con respuestas veraces, útiles y basadas en hechos.",
        },
        {"role": "user", "content": prompt},
    ]

    try:
        # Cargar la clave API desde la variable de entorno
        api_key = os.environ['HUGGINGFACE_TOKEN']

        # URL de la API de Hugging Face para la generación de texto
        api_url = "https://api-inference.huggingface.co/models/HuggingFaceH4/zephyr-7b-beta"

        # Cabeceras para la solicitud
        headers = {"Authorization": f"Bearer {api_key}"}

        # Datos para enviar en la solicitud POST
        data = {
            "inputs": prompt,
            "parameters": {
                "max_new_tokens": max_new_tokens,
                "temperature": 0.7,
                "top_k": 50,
                "top_p": 0.95
            }
        }

        # Realizamos la solicitud POST
        response = requests.post(api_url, headers=headers, json=data)

        # Extraer respuesta
        respuesta = response.json()[0]["generated_text"]
        return respuesta
    except Exception as e:
        return f"An error occurred: {e}"

# Clasificador LLM con prompts few-shot
few_shot_prompt = """
Pregunta: ¿Cuál es la población de Argentina?
Respuesta: La población de Argentina es aproximadamente 45 millones de personas según los últimos datos disponibles.

Pregunta: ¿Qué es el PIB de Brasil?
Respuesta: El Producto Interno Bruto de Brasil es un indicador económico que refleja el valor total de los bienes y servicios producidos en Brasil durante un año. Su valor estimado es de 1.8 billones de USD.

Pregunta: ¿Cuál es la capital de Argentina?
Respuesta: La capital de Argentina es Buenos Aires.

Pregunta: ¿Cuál es la población mundial?
Respuesta: La población mundial es de aproximadamente 7.8 mil millones de personas según las últimas estimaciones.

Pregunta: {question}
Respuesta:
"""

def classify_with_llm(question):
    prompt = few_shot_prompt.format(question=question)
    response = generate_answer(prompt)
    if "Argentina" in response:
        return 1
    elif "Brasil" in response:
        return 2
    elif "población" in response:
        return 3
    else:
        return 0

# Datos de prueba
test_data = [
    {'text': '¿Cuál es la población de Argentina?', 'label': 1},
    {'text': '¿Dónde está Buenos Aires?', 'label': 1},
    {'text': '¿Qué es el PIB de Brasil?', 'label': 2},
    {'text': '¿Cuál es la población mundial?', 'label': 3}
]

# Evaluar el modelo basado en LLM
labels = [item['label'] for item in test_data]
y_pred_llm = [classify_with_llm(item['text']) for item in test_data]
accuracy_llm = accuracy_score(labels, y_pred_llm)
llm_report = classification_report(labels, y_pred_llm)
llm_confusion_matrix = confusion_matrix(labels, y_pred_llm)

print(f"LLM Classifier Accuracy: {accuracy_llm}")
print(llm_report)
print(llm_confusion_matrix)


LLM Classifier Accuracy: 0.5
              precision    recall  f1-score   support

           1       0.50      1.00      0.67         2
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         1

    accuracy                           0.50         4
   macro avg       0.17      0.33      0.22         4
weighted avg       0.25      0.50      0.33         4

[[2 0 0]
 [1 0 0]
 [1 0 0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**Clasificador basado en un modelo entrenado con ejemplos y embeddings**

In [16]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sentence_transformers import SentenceTransformer

# Cargar el modelo de SentenceTransformers
embedding_model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

# Función para generar embeddings
def get_embeddings(texts, model):
    return model.encode(texts)

# Datos de entrenamiento con ejemplos y etiquetas
train_data = [
    {'text': 'La población de Argentina es de aproximadamente 45 millones de personas.', 'label': 1},
    {'text': 'El PIB de Brasil es de 1.8 billones de USD.', 'label': 2},
    {'text': 'Buenos Aires es la capital de Argentina.', 'label': 1},
    {'text': 'La población mundial es de aproximadamente 7.8 mil millones de personas.', 'label': 3}
]

# Extraer textos y etiquetas del conjunto de entrenamiento
train_texts = [item['text'] for item in train_data]
train_labels = [item['label'] for item in train_data]

# Generar embeddings para los textos de entrenamiento
train_embeddings = get_embeddings(train_texts, embedding_model)

# Entrenar el modelo de regresión logística
clf = LogisticRegression(max_iter=1000, random_state=42)
clf.fit(train_embeddings, train_labels)

# Nuevos textos no etiquetados para probar (datos de prueba reales)
new_texts = [
    '¿Cuántos habitantes tiene Buenos Aires?',
    '¿Qué es el producto interno bruto de Argentina?',
    '¿Cuál es la población total del planeta?',
    '¿Dónde está ubicada la capital de Brasil?'
]

# Generar embeddings para los nuevos textos
new_embeddings = get_embeddings(new_texts, embedding_model)

# Predicción para los nuevos textos
new_predictions = clf.predict(new_embeddings)

# Etiquetas verdaderas para los nuevos textos (esto debes generarlo manualmente)
true_labels = [1, 1, 3, 2]

# Calcular métricas
accuracy = accuracy_score(true_labels, new_predictions)
report = classification_report(true_labels, new_predictions)
conf_matrix = confusion_matrix(true_labels, new_predictions)

print(f"Accuracy del clasificador basado en embeddings: {accuracy}")
print(report)
print(conf_matrix)


Accuracy del clasificador basado en embeddings: 0.75
              precision    recall  f1-score   support

           1       0.67      1.00      0.80         2
           2       0.00      0.00      0.00         1
           3       1.00      1.00      1.00         1

    accuracy                           0.75         4
   macro avg       0.56      0.67      0.60         4
weighted avg       0.58      0.75      0.65         4

[[2 0 0]
 [1 0 0]
 [0 0 1]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**Comparacion**

In [17]:
# Comparar los dos modelos
if accuracy > accuracy_llm:
    print("El clasificador basado en embeddings y modelo entrenado es mejor.")
else:
    print("El clasificador basado en LLM es mejor.")

El clasificador basado en embeddings y modelo entrenado es mejor.


El modelo basado en embeddings probablemente está dando mejores resultados porque está específicamente optimizado para esta tarea mediante el entrenamiento supervisado. El modelo de regresión logística está entrenado directamente con datos etiquetados, lo que significa que ha aprendido específicamente a distinguir entre las diferentes clases (población de Argentina, PIB de Brasil, etc.) basándose en las características de los embeddings.

**Implementacion del ChatBot**

In [ ]:
!pip install langdetect


In [19]:
from langdetect import detect

def detect_language(text):
    try:
        return detect(text)
    except:
        return "unknown"


In [22]:
def process_chromadb_results(results):
    """
    Procesa los resultados de ChromaDB para extraer y formatear los fragmentos relevantes.
    """
    if not results or 'documents' not in results:
        return "No se encontraron documentos relevantes."

    # Extraer los fragmentos de texto
    documents = results['documents'][0]

    # Combinar los fragmentos en una respuesta coherente
    combined_text = "\n".join(documents[:3])
    return combined_text

def chatbot_response(query, model):
    # Detectar el idioma de la consulta
    language = detect_language(query)

    # Análisis del prompt usando NER y lematización
    entities, lemmas = analyze_query(query)

    # Priorizar la búsqueda y procesar los resultados
    chromadb_results = search_chromadb(' '.join(lemmas), collection, model)
    if chromadb_results:
        processed_result = process_chromadb_results(chromadb_results)
        return generate_answer(f"Información relevante encontrada en ChromaDB: {processed_result}")

    csv_results = search_csv(' '.join(entities), population_data)
    if csv_results:
        return generate_answer(f"Información relevante encontrada en el CSV: {csv_results}")

    graph_results = search_graph(' '.join(entities))
    if graph_results:
        return generate_answer(f"Información relevante encontrada en la Base de Datos de Grafos: {graph_results}")

    return "No se ha encontrado información relevante."


In [21]:

def start_chatbot():
    print("¡Hola! Puedes hacerme preguntas en español o inglés. Escribe 'salir' para terminar.")
    while True:
        query = input("Tú: ")
        if query.lower() in ['salir', 'exit']:
            print("Chatbot: ¡Hasta luego!")
            break
        response = chatbot_response(query, embedding_model)
        print(f"Chatbot: {response}")

# Iniciar el chatbot
start_chatbot()

¡Hola! Puedes hacerme preguntas en español o inglés. Escribe 'salir' para terminar.
Tú: salir
Chatbot: ¡Hasta luego!
